server:
  port: 0

spring:
  application:
    name: inventory-service
  datasource:
    username: inventory
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_URL}/inventory

eureka:
  client:
    registerWithEureka: true
    enableServiceDiscovery: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/